# Generated by Django 5.0.6 on 2024-08-12 18:41

import ckeditor.fields
import datetime
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('text', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', null=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(blank=True, max_length=30, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('answer', models.CharField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacyPolicy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shippingPolicy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('returnPolicy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cancellationPolicy', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnsAndExchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('opening_hours', models.CharField(blank=True, default='', null=True)),
                ('closing_hours', models.CharField(blank=True, default='', null=True)),
                ('map_link', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('faqBanner', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('aboutUsBanner', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('faqBannerTitle', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('storeLocatorBanner', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('storeLocatorBannerTitle', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('social_link', models.TextField(default='')),
                ('icon', models.ImageField(default='', upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('directionLink', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('timings', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_creation_time', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 0, 11, 55, 240688))),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='uniform_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_discount_applied', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.CharField(blank=True, max_length=3, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_status', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 0, 11, 55, 247906))),
                ('discount_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uniform_app.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniform_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniform_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('credit card', 'Credit card'), ('cod', 'Cash on delivery')], max_length=20)),
                ('credit_card_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('card_verification_number', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniform_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField()),
                ('name', models.CharField(default='', max_length=100)),
                ('short_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('description', models.CharField(default='')),
                ('item_type', models.CharField(choices=[('security', 'Security'), ('police', 'Police'), ('sheriff', 'Sheriff'), ('fire', 'Fire'), ('others', 'Others')], default='others', max_length=20)),
                ('mrp', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_applied_in', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('XS', models.BigIntegerField(blank=True, null=True)),
                ('S', models.BigIntegerField(blank=True, null=True)),
                ('M', models.BigIntegerField(blank=True, null=True)),
                ('L', models.BigIntegerField(blank=True, null=True)),
                ('XL', models.BigIntegerField(blank=True, null=True)),
                ('XXL', models.BigIntegerField(blank=True, null=True)),
                ('XXXL', models.BigIntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='Images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('color', models.CharField(default='', max_length=25)),
                ('prints', models.CharField(blank=True, max_length=25, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('material_care', models.CharField(blank=True, max_length=250, null=True)),
                ('is_coupon_applied', models.BooleanField(default=True)),
                ('coupons_amount', models.CharField(blank=True, max_length=150, null=True)),
                ('coupon', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_days', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_charges', models.BigIntegerField(blank=True, null=True)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_featured_product', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('on_sale_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_ready_to_ship', models.BooleanField(default=False)),
                ('made_in', models.CharField(blank=True, max_length=30, null=True)),
                ('likes', models.BigIntegerField(default=0)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniform_app.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniform_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('customization', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_status', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniform_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='uniform_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XS', models.BigIntegerField(blank=True, null=True)),
                ('S', models.BigIntegerField(blank=True, null=True)),
                ('M', models.BigIntegerField(blank=True, null=True)),
                ('L', models.BigIntegerField(blank=True, null=True)),
                ('XL', models.BigIntegerField(blank=True, null=True)),
                ('XXL', models.BigIntegerField(blank=True, null=True)),
                ('XXXL', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('sales_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 13, 0, 11, 55, 246725))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='uniform_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniform_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniform_app.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
