# Generated by Django 5.0.6 on 2024-08-17 11:05

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigAndTallInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('size_and_dimension', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True)),
                ('additional_information', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 16, 35, 12, 530497)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 16, 35, 12, 532490)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 16, 35, 12, 519526)),
        ),
    ]
