# Generated by Django 5.0.6 on 2024-08-18 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0002_bigandtallinquiry_remove_faq_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 13, 42, 30, 731273)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 13, 42, 30, 736205)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 13, 42, 30, 715605)),
        ),
    ]
