# Generated by Django 5.0.6 on 2024-08-24 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0004_blog_alter_cart_created_at_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='embroider_text',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 12, 51, 32, 595166)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 12, 51, 32, 595166)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 12, 51, 32, 594136)),
        ),
    ]
