# Generated by Django 5.0.6 on 2024-08-26 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0007_alter_cart_created_at_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 15, 31, 9, 203315)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 15, 31, 9, 202334)),
        ),
    ]
