# Generated by Django 5.0.6 on 2024-08-30 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0008_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigandtallinquiry',
            name='additional_information',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bigandtallinquiry',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 33, 30, 590781)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 33, 30, 589747)),
        ),
    ]
