# Generated by Django 5.0.6 on 2024-08-30 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0009_alter_bigandtallinquiry_additional_information_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='HomeBanner',
        ),
        migrations.RenameField(
            model_name='homebanner',
            old_name='banner',
            new_name='banner_image',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 48, 40, 398176)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 17, 48, 40, 398176)),
        ),
    ]
