# Generated by Django 5.0.6 on 2024-08-30 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0013_alter_cart_created_at_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_type',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 22, 30, 50, 333442)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 22, 30, 50, 333442)),
        ),
    ]
