# Generated by Django 5.0.6 on 2024-08-30 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0014_rename_item_type_product_menu_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 22, 37, 6, 39698)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 22, 37, 6, 38710)),
        ),
    ]
