# Generated by Django 5.0.6 on 2024-09-04 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0015_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 15, 45, 14, 545331)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 15, 45, 14, 543301)),
        ),
        migrations.AlterField(
            model_name='useraddressdetails',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraddressdetails',
            name='first_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraddressdetails',
            name='last_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
