# Generated by Django 5.0.6 on 2024-09-04 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0016_alter_cart_created_at_alter_user_otp_creation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='coupons_amount',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 18, 7, 11, 349360)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 18, 7, 11, 348360)),
        ),
    ]
