# Generated by Django 5.0.6 on 2024-09-04 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0017_remove_product_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_coupon_applied',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 18, 8, 18, 896026)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 18, 8, 18, 894992)),
        ),
    ]
