# Generated by Django 5.0.6 on 2024-09-04 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0018_remove_product_is_coupon_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 18, 18, 15, 859250)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 18, 18, 15, 858216)),
        ),
    ]
