# Generated by Django 5.0.6 on 2024-09-05 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0019_alter_cart_created_at_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 10, 54, 43, 710140)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.CharField(choices=[('security', 'Security'), ('police', 'Police'), ('sheriff', 'Sheriff'), ('fire', 'Fire'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='prints',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 10, 54, 43, 710140)),
        ),
    ]
