# Generated by Django 5.0.6 on 2024-09-05 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0020_alter_cart_color_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 10, 59, 37, 248070)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 10, 59, 37, 248070)),
        ),
    ]
