# Generated by Django 5.0.6 on 2024-09-05 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0021_alter_cart_created_at_alter_cart_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 11, 26, 50, 393158)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='image1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 11, 26, 50, 377497)),
        ),
    ]
