# Generated by Django 5.0.6 on 2024-09-09 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0024_alter_cart_created_at_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 15, 41, 37, 814627)),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='pincode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='pincode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 15, 41, 37, 813629)),
        ),
    ]
