# Generated by Django 5.0.6 on 2024-09-09 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0025_alter_cart_created_at_alter_companyinfo_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 16, 14, 26, 325967)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 16, 14, 26, 324970)),
        ),
    ]
