# Generated by Django 5.0.6 on 2024-09-11 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0026_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_applied_in',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 12, 29, 24, 783166)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 12, 29, 24, 767511)),
        ),
    ]
