# Generated by Django 5.0.6 on 2024-09-11 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0027_remove_product_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='embroider_text',
            new_name='l_embroider',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='patches',
            new_name='l_patches',
        ),
        migrations.AddField(
            model_name='cart',
            name='m_embroider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='m_patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='s_embroider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='s_patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xl_embroider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xl_patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xs_embroider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xs_patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xxl_embroider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xxl_patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xxxl_embroider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='xxxl_patches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 11, 6, 272714)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 11, 6, 271684)),
        ),
    ]
