# Generated by Django 5.0.6 on 2024-09-11 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0028_rename_embroider_text_cart_l_embroider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='has_embroidery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='has_patch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 47, 9, 189427)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 47, 9, 188392)),
        ),
    ]
