# Generated by Django 5.0.6 on 2024-09-12 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0030_alter_cart_created_at_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 12, 58, 25, 217697)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 12, 58, 25, 201044)),
        ),
    ]
