# Generated by Django 5.0.6 on 2024-09-12 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0032_remove_product_likes_remove_product_made_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_charges',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 13, 6, 51, 709536)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 13, 6, 51, 709536)),
        ),
    ]
