# Generated by Django 5.0.6 on 2024-09-12 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0033_remove_product_shipping_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_care',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prints',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 13, 31, 14, 841878)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 13, 31, 14, 839446)),
        ),
    ]
