# Generated by Django 5.0.6 on 2024-09-12 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0036_alter_cart_created_at_alter_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 17, 36, 29, 208128)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 17, 36, 29, 201636)),
        ),
    ]
