# Generated by Django 5.0.6 on 2024-09-14 07:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0037_remove_product_short_name_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='first_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='last_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 12, 36, 10, 722829)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 12, 36, 10, 722829)),
        ),
    ]
