# Generated by Django 5.0.6 on 2024-09-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0039_alter_cart_created_at_alter_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customization',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 13, 32, 49, 886768)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 13, 32, 49, 885789)),
        ),
    ]
