# Generated by Django 5.0.6 on 2024-09-21 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0040_remove_orderitem_customization_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressdetails',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 15, 39, 6, 222394)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 15, 39, 6, 222394)),
        ),
    ]
