# Generated by Django 5.0.6 on 2024-09-21 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0041_rename_phone_number_useraddressdetails_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 15, 46, 20, 971555)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 15, 46, 20, 964578)),
        ),
    ]
