# Generated by Django 5.0.6 on 2024-09-23 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0044_shippingaddress_address_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressdetails',
            name='order',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 18, 1, 8, 525874)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 18, 1, 8, 525874)),
        ),
    ]
