# Generated by Django 5.0.6 on 2024-09-27 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0045_remove_useraddressdetails_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sales_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 16, 47, 28, 793981)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 27, 16, 47, 28, 792980)),
        ),
    ]
