# Generated by Django 5.0.6 on 2024-10-05 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0046_orderitem_sales_rate_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 12, 51, 5, 31426)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='In Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 12, 51, 5, 14828)),
        ),
    ]
