# Generated by Django 5.0.6 on 2024-10-05 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0049_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 18, 15, 966689)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 18, 15, 966689)),
        ),
    ]
