# Generated by Django 5.0.6 on 2024-10-05 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0050_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='applied_in',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], default='Percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='offer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='offer_percentage',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 19, 11, 574281)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 19, 11, 574281)),
        ),
    ]
