# Generated by Django 5.0.6 on 2024-10-05 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0051_homebanner_applied_in_homebanner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 22, 25, 114384)),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 18, 22, 25, 98731)),
        ),
    ]
