# Generated by Django 5.0.6 on 2024-10-06 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0053_category_banner_product_banner_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_sale_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_in',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='others', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 11, 43, 21, 605994)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 11, 43, 21, 605994)),
        ),
    ]
