# Generated by Django 5.0.6 on 2024-10-06 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0054_remove_product_on_sale_amount_product_discount_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='banner_options',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 13, 33, 16, 580690)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 13, 33, 16, 572657)),
        ),
    ]
