# Generated by Django 5.0.6 on 2024-10-06 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0056_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 16, 48, 41, 145214)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 16, 48, 41, 143189)),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
