# Generated by Django 5.0.6 on 2024-10-07 14:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0058_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='applied_in',
        ),
        migrations.RemoveField(
            model_name='homebanner',
            name='offer_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_amount',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 20, 6, 2, 982595)),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniform_app.homebanner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 20, 6, 2, 982595)),
        ),
    ]
