# Generated by Django 5.0.6 on 2024-10-10 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0059_remove_homebanner_applied_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_on_sale',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 11, 9, 30, 345405)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 11, 9, 30, 345405)),
        ),
    ]
