# Generated by Django 5.0.6 on 2024-10-11 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0062_alter_cart_created_at_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='menu',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 0, 47, 5, 959225)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 0, 47, 5, 958196)),
        ),
    ]
