# Generated by Django 5.0.6 on 2024-10-12 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0063_remove_product_menu_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 12, 44, 22, 138514)),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='offer_percentage',
            field=models.IntegerField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 12, 44, 22, 138514)),
        ),
    ]
