# Generated by Django 5.0.6 on 2024-10-12 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0064_alter_homebanner_options_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='size_chart',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 13, 37, 36, 735685)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 13, 37, 36, 728687)),
        ),
    ]
