# Generated by Django 5.0.6 on 2024-10-14 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0065_setting_size_chart_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.AddField(
            model_name='product',
            name='show_patches_and_embroider_on_UI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 12, 24, 14, 620000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 12, 24, 14, 620000)),
        ),
    ]
