# Generated by Django 5.0.6 on 2024-10-14 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0066_remove_product_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 19, 39, 41, 672143)),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 19, 39, 41, 656490)),
        ),
    ]
