# Generated by Django 5.0.6 on 2024-10-18 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0068_product_rating_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='aboutUsBanner',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='faqBanner',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='faqBannerTitle',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='storeLocatorBanner',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='storeLocatorBannerTitle',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 11, 3, 58, 500754)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='l_embroider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='l_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='m_embroider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='m_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='s_embroider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='s_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xl_embroider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xl_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xs_embroider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xs_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xxl_embroider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xxl_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xxxl_embroider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='xxxl_patches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 11, 3, 58, 500754)),
        ),
    ]
