# Generated by Django 5.0.6 on 2024-10-18 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0069_remove_setting_aboutusbanner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='bigandtallinquiry',
            options={'verbose_name_plural': 'Billing and Tall Inquiry'},
        ),
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing Address'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name_plural': 'Company Info'},
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name_plural': 'Contact Request'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'Discount'},
        ),
        migrations.AlterModelOptions(
            name='emailsubscriptionrequest',
            options={'verbose_name_plural': 'Email Subscription Request'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name_plural': 'Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='policies',
            options={'verbose_name_plural': 'Policy'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='requestcatalog',
            options={'verbose_name_plural': 'Request Catalog'},
        ),
        migrations.AlterModelOptions(
            name='returnsandexchanges',
            options={'verbose_name_plural': 'Return and Exchange'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name_plural': 'Setting'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name_plural': 'Shipping'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social Media'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name_plural': 'Term and Conditions'},
        ),
        migrations.AlterModelOptions(
            name='useraddressdetails',
            options={'verbose_name_plural': 'User Address Details'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 15, 54, 1, 336329)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 15, 54, 1, 336329)),
        ),
    ]
