# Generated by Django 5.0.6 on 2024-10-19 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0070_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 11, 21, 23, 500065)),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 11, 21, 23, 484440)),
        ),
    ]
