# Generated by Django 5.0.6 on 2024-10-19 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0071_alter_cart_created_at_alter_setting_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 11, 46, 18, 72088)),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 11, 46, 18, 56450)),
        ),
    ]
