# Generated by Django 5.0.6 on 2024-10-19 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0072_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 11, 51, 57, 375382)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 11, 51, 57, 375382)),
        ),
    ]
