# Generated by Django 5.0.6 on 2024-10-21 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0073_billingaddress_order_date_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 14, 36, 2, 152708)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 14, 36, 2, 141415)),
        ),
    ]
