# Generated by Django 5.0.6 on 2024-10-23 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0074_order_paypal_access_token_order_paypal_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', null=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leave Feedback',
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 19, 48, 0, 993581)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 19, 48, 0, 985512)),
        ),
    ]
