# Generated by Django 5.0.6 on 2024-10-23 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0075_leavefeedback_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 20, 36, 1, 345032)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 20, 36, 1, 345032)),
        ),
    ]
