# Generated by Django 5.0.6 on 2024-10-24 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0076_alter_billingaddress_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 12, 57, 2, 214035)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 12, 57, 2, 214035)),
        ),
        migrations.AlterField(
            model_name='useraddressdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
