# Generated by Django 5.0.6 on 2024-11-06 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0079_product_is_cancellable_product_is_exchangeable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='max_cancellation_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='max_exchange_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='max_return_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 13, 56, 5, 457353)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 13, 56, 5, 441733)),
        ),
    ]
