# Generated by Django 5.0.6 on 2024-11-06 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0080_setting_max_cancellation_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='restocking_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 15, 12, 25, 259019)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 15, 12, 25, 244060)),
        ),
    ]
