# Generated by Django 5.0.6 on 2024-11-07 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0081_orderitem_cancelled_at_orderitem_restocking_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 11, 55, 36, 481443)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], default='Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return Initiated', 'Return Initiated'), ('Returned', 'Returned'), ('Exchange Initiated', 'Exchange Initiated'), ('Exchanged', 'Exchanged'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded')], default='In Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 11, 55, 36, 473964)),
        ),
    ]
