# Generated by Django 5.0.6 on 2024-11-13 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0084_alter_cart_created_at_alter_user_otp_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_reason',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_by',
            field=models.CharField(choices=[('None', 'None'), ('Admin', 'Admin'), ('User', 'User')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 12, 0, 33, 572595)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 12, 0, 33, 564614)),
        ),
    ]
