# Generated by Django 5.0.6 on 2024-11-16 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0085_orderitem_cancel_reason_orderitem_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 16, 9, 23, 71782)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 16, 9, 23, 63768)),
        ),
    ]
