# Generated by Django 5.0.6 on 2024-11-18 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0087_product_embroider_price_product_logo_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='credit_note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 16, 0, 54, 504723)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 16, 0, 54, 504723)),
        ),
    ]
