# Generated by Django 5.0.6 on 2024-11-19 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0088_orderitem_credit_note_number_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 17, 3, 13, 274165)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 17, 3, 13, 273130)),
        ),
    ]
