# Generated by Django 5.0.6 on 2024-11-20 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0089_product_customization_comment_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='after_customization_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 0, 41, 22, 408483)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 0, 41, 22, 389532)),
        ),
    ]
