# Generated by Django 5.0.6 on 2024-11-25 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0091_orderitem_after_customization_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_initiated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_authorization_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_initiated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_by',
            field=models.CharField(choices=[('None', 'None'), ('Admin', 'Admin'), ('User', 'User')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_item_image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/Return/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_item_image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/Return/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 11, 11, 10, 407714)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return Initiated', 'Return Initiated'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Parcel Pickup Initiated for Return', 'Parcel Pickup Initiated for Return'), ('Parcel Picked Up for Return', 'Parcel Picked Up for Return'), ('Returned', 'Returned'), ('Exchange Initiated', 'Exchange Initiated'), ('Exchange Approved', 'Exchange Approved'), ('Exchange Rejected', 'Exchange Rejected'), ('Parcel Pickup Initiated for Exchange', 'Parcel Pickup Initiated for Exchange'), ('Parcel Picked Up for Exchange', 'Parcel Picked Up for Exchange'), ('Exchanged', 'Exchanged'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded')], default='In Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 11, 11, 10, 398737)),
        ),
    ]
