# Generated by Django 5.0.6 on 2024-11-25 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0092_orderitem_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='courier_service_provider_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 13, 55, 44, 5428)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 13, 55, 43, 994107)),
        ),
    ]
