# Generated by Django 5.0.6 on 2024-11-25 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0093_orderitem_courier_service_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 16, 53, 11, 777383)),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 16, 53, 11, 761765)),
        ),
    ]
