# Generated by Django 5.0.6 on 2024-11-28 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0095_order_stripe_session_id_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='embroider',
            field=models.BooleanField(default=False, verbose_name='Embroider / Name'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='patches',
            field=models.BooleanField(default=False, verbose_name='Patches / Batches'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='security_batches',
            field=models.BooleanField(default=False, verbose_name='Security id'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 13, 21, 43, 974497)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='embroider_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Embroider / Name Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='patches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Patches / Batches Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='security_batches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security id Price'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 13, 21, 43, 963710)),
        ),
    ]
