# Generated by Django 5.0.6 on 2024-11-28 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0096_orderitem_embroider_orderitem_logo_orderitem_patches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='embroider',
            field=models.BooleanField(default=False, verbose_name='Embroider / Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='patches',
            field=models.BooleanField(default=False, verbose_name='Patches / Batches'),
        ),
        migrations.AddField(
            model_name='product',
            name='security_batches',
            field=models.BooleanField(default=False, verbose_name='Security id'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 13, 26, 35, 404627)),
        ),
        migrations.AlterField(
            model_name='product',
            name='embroider_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Embroider / Name Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='patches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Patches / Batches Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='security_batches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security id Price'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 13, 26, 35, 394609)),
        ),
    ]
