# Generated by Django 5.0.6 on 2024-11-29 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0098_alter_social_options_orderitem_exchange_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='exchange_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 13, 29, 43, 264932)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 13, 29, 43, 256954)),
        ),
    ]
