# Generated by Django 5.0.6 on 2024-11-29 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0099_orderitem_exchange_reason_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='after_customization_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='embroider',
            field=models.BooleanField(default=False, verbose_name='Embroider / Name'),
        ),
        migrations.AddField(
            model_name='cart',
            name='logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='patches',
            field=models.BooleanField(default=False, verbose_name='Patches / Batches'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='security_batches',
            field=models.BooleanField(default=False, verbose_name='Security id'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 15, 53, 5, 66518)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 15, 53, 5, 49240)),
        ),
    ]
