# Generated by Django 5.0.6 on 2024-11-29 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0100_cart_after_customization_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customization_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 17, 12, 34, 818864)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 17, 12, 34, 813773)),
        ),
    ]
