# Generated by Django 5.0.6 on 2024-12-01 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0101_cart_customization_comment_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='embroider_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Embroider / Name Price'),
        ),
        migrations.AddField(
            model_name='cart',
            name='logo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='patches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Patches / Batches Price'),
        ),
        migrations.AddField(
            model_name='cart',
            name='security_batches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security id Price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 11, 6, 41, 771484)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 11, 6, 41, 758629)),
        ),
    ]
