# Generated by Django 5.0.6 on 2024-12-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0104_orderitem_invoice_number_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 12, 38, 0, 310594)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 12, 38, 0, 294931)),
        ),
    ]
