# Generated by Django 5.0.6 on 2024-12-05 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0105_alter_cart_created_at_alter_user_otp_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='exchange_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='exchange_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='parent_exchange_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 15, 34, 43, 350386)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 15, 34, 43, 337425)),
        ),
    ]
