# Generated by Django 5.0.6 on 2024-12-26 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0108_alter_cart_created_at_alter_orderitem_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchange_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='parent_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paypal_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paypal_order_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_percentage',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stripe_session_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='type',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Exchanged', 'Exchanged'), ('Returned', 'Returned')], default='Sold', max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 12, 29, 59, 464476)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='embroider',
            field=models.BooleanField(default=False, verbose_name='Embroider'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='embroider_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Embroider Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return Initiated', 'Return Initiated'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Parcel Pickup Initiated for Return', 'Parcel Pickup Initiated for Return'), ('Parcel Picked Up for Return', 'Parcel Picked Up for Return'), ('Returned', 'Returned'), ('Exchange Initiated', 'Exchange Initiated'), ('Exchange Approved', 'Exchange Approved'), ('Exchange Rejected', 'Exchange Rejected'), ('Parcel Pickup Initiated for Exchange', 'Parcel Pickup Initiated for Exchange'), ('Parcel Picked Up for Exchange', 'Parcel Picked Up for Exchange'), ('Exchanged', 'Exchanged'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded'), ('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Order Processing', 'Order Processing'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Out For Delivery', 'Out For Delivery'), ('Attempted Delivery', 'Attempted Delivery')], default='Order placed', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='embroider_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Embroider Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_patches_and_embroider_on_UI',
            field=models.BooleanField(default=False, verbose_name='Show Customization Details'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 12, 29, 59, 456496)),
        ),
    ]
