# Generated by Django 5.0.6 on 2024-12-26 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0109_orderitem_customization_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 12, 32, 5, 492684)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 12, 32, 5, 484705)),
        ),
        migrations.DeleteModel(
            name='ReturnExchangeRequest',
        ),
    ]
