# Generated by Django 5.0.6 on 2024-12-27 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0110_alter_cart_created_at_alter_user_otp_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 13, 7, 19, 230338)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Exchanged', 'Exchanged'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Sold', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 13, 7, 19, 222325)),
        ),
    ]
