# Generated by Django 5.0.6 on 2024-12-27 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0111_alter_cart_created_at_alter_orderitem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='exchanged_item_image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/Exchange/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='exchanged_item_image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Images/Exchange/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 15, 49, 16, 908079)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 15, 49, 16, 908079)),
        ),
    ]
