# Generated by Django 5.0.6 on 2025-01-02 07:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0113_feedbackrequest_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uniform_app.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 12, 47, 35, 787112)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 12, 47, 35, 773120)),
        ),
    ]
