# Generated by Django 5.0.6 on 2025-01-03 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0114_feedbackrequest_product_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='free_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='free_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_free_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 10, 55, 3, 98625)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 10, 55, 3, 91608)),
        ),
    ]
