# Generated by Django 5.0.6 on 2025-01-15 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0115_cart_free_size_product_free_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 12, 35, 662090)),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100, verbose_name='Exchange payment status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 12, 35, 650089)),
        ),
    ]
