# Generated by Django 5.0.6 on 2025-01-15 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0116_alter_cart_created_at_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='banner_type',
            field=models.CharField(choices=[('None', 'None'), ('Bestseller', 'Bestseller'), ('Featured', 'Featured')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 36, 14, 687758)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 12, 36, 14, 679779)),
        ),
    ]
