# Generated by Django 5.0.6 on 2025-01-15 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0117_homebanner_banner_type_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 18, 8, 59, 125895)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tax amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 18, 8, 59, 117914)),
        ),
    ]
