# Generated by Django 5.0.6 on 2025-01-16 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0118_alter_cart_created_at_alter_orderitem_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 15, 8, 34, 644233)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', max_length=255, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 15, 8, 34, 636256)),
        ),
    ]
