# Generated by Django 5.0.6 on 2025-01-23 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0121_leavefeedback_created_at_requestcatalog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 14, 8, 22, 355042)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tax amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 14, 8, 22, 355042)),
        ),
    ]
