# Generated by Django 5.0.6 on 2025-01-27 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0122_alter_cart_created_at_alter_orderitem_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 10, 42, 11, 216770)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customization_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Customization Price ($)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Refund amount ($)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sales_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sales rate ($)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal ($)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tax amount ($)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total amount ($)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 10, 42, 11, 201778)),
        ),
    ]
