# Generated by Django 5.0.6 on 2025-02-13 09:29

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0123_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 14, 57, 51, 957104)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 14, 57, 51, 941111)),
        ),
    ]
