# Generated by Django 5.0.6 on 2025-02-19 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0124_feedbackrequest_created_at_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='printed_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='printed_id_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='security_id_on_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='security_id_on_back_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printed_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printed_id_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='security_id_on_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='security_id_on_back_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='printed_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='printed_id_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='security_id_on_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='security_id_on_back_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 14, 16, 53, 649414)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='security_batches',
            field=models.BooleanField(default=False, verbose_name='Security ID on Back and Chest'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='security_batches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security ID on Back and Chest'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='security_batches',
            field=models.BooleanField(default=False, verbose_name='Security ID on Back and Chest'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='security_batches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security ID on Back and Chest'),
        ),
        migrations.AlterField(
            model_name='product',
            name='security_batches',
            field=models.BooleanField(default=False, verbose_name='Security ID on Back and Chest'),
        ),
        migrations.AlterField(
            model_name='product',
            name='security_batches_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security ID on Back and Chest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 14, 16, 53, 634419)),
        ),
    ]
