# Generated by Django 5.0.6 on 2025-11-09 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform_app', '0125_cart_printed_id_cart_printed_id_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 17, 10, 30, 178322)),
        ),
        migrations.AlterField(
            model_name='product',
            name='embroider',
            field=models.BooleanField(default=False, verbose_name='Embroider'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 17, 10, 30, 169307)),
        ),
    ]
