# Generated by Django 4.1.3 on 2024-07-17 06:18

import back_site.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20, validators=[back_site.models.validate_phone_number])),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bridal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[back_site.models.validate_title])),
                ('subtitle1', models.TextField(blank=True, default='', max_length=250)),
                ('subtitle2', models.TextField(blank=True, default='', max_length=250)),
                ('bridalImage', models.ImageField(upload_to='Images/')),
            ],
            options={
                'verbose_name_plural': 'Bridal Description',
            },
        ),
        migrations.CreateModel(
            name='BridalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contactNumber', models.BigIntegerField(verbose_name='Contact Number')),
                ('zipCode', models.BigIntegerField()),
                ('message', models.TextField()),
                ('dateOfWedding', models.DateField(blank=True, null=True, verbose_name='Date Of Wedding')),
                ('createdDate', models.DateField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('termsAndCondition', models.BooleanField(verbose_name='Terms And Conditions')),
            ],
            options={
                'verbose_name_plural': 'Bridal Requests',
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField(blank=True, null=True)),
                ('subtitle1', models.CharField(max_length=255)),
                ('content2', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cancellation Policy',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle1', models.CharField(max_length=255)),
                ('content1', models.TextField(blank=True, null=True)),
                ('subtitle2', models.CharField(blank=True, max_length=255, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('subtitle3', models.CharField(blank=True, max_length=255, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('contactUsImage', models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='Contact Us Image')),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Copyright Text',
            },
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promocode', models.CharField(max_length=10)),
                ('discount_percentage', models.BigIntegerField(validators=[back_site.models.validate_discount])),
                ('maximum_discount_price', models.BigIntegerField(validators=[back_site.models.validate_integer_field])),
                ('expiry_date', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAndShippingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField(blank=True, null=True)),
                ('title2', models.CharField(max_length=255)),
                ('content2', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery & Shipping Policy',
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('subscribe', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': 'Email Subsciptions',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ List',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magzine_img', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='FooterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('subtitle2', models.CharField(max_length=255)),
                ('content2', models.TextField()),
                ('subtitle3', models.CharField(max_length=255)),
                ('content3', models.TextField()),
                ('subtitle4', models.CharField(max_length=255)),
                ('content4', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Footer Description',
            },
        ),
        migrations.CreateModel(
            name='Home_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantNoticeToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point1', models.CharField(max_length=200)),
                ('point2', models.CharField(blank=True, max_length=200, null=True)),
                ('point3', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Important Notice On Cart',
            },
        ),
        migrations.CreateModel(
            name='InstagramCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_home_link', models.CharField(max_length=255)),
                ('instagram_post1', models.ImageField(upload_to='Images/')),
                ('instagram_post1_link', models.CharField(max_length=255)),
                ('instagram_post2', models.ImageField(upload_to='Images/')),
                ('instagram_post2_link', models.CharField(max_length=255)),
                ('instagram_post3', models.ImageField(upload_to='Images/')),
                ('instagram_post3_link', models.CharField(max_length=255)),
                ('instagram_post4', models.ImageField(upload_to='Images/')),
                ('instagram_post4_link', models.CharField(max_length=255)),
                ('instagram_post5', models.ImageField(upload_to='Images/')),
                ('instagram_post5_link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Instagram Posts',
            },
        ),
        migrations.CreateModel(
            name='ItDesignContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopImage1', models.ImageField(upload_to='Images/')),
                ('TopImage2', models.ImageField(upload_to='Images/')),
                ('HeaderText', models.CharField(max_length=50)),
                ('description1', models.TextField(max_length=200)),
                ('description2', models.TextField(max_length=500)),
                ('descriptionHighlight', models.CharField(max_length=100)),
                ('sliderImg1', models.ImageField(upload_to='Images/')),
                ('sliderImg2', models.ImageField(upload_to='Images/')),
                ('sliderImg3', models.ImageField(upload_to='Images/')),
                ('contactHeader', models.CharField(max_length=50)),
                ('contactDescription', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogoAndCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Images/')),
                ('cover1', models.ImageField(upload_to='Images/')),
                ('cover2', models.ImageField(upload_to='Images/')),
                ('cover3', models.ImageField(upload_to='Images/')),
                ('cover4', models.ImageField(upload_to='Images/')),
                ('cover5', models.ImageField(upload_to='Images/')),
            ],
            options={
                'verbose_name_plural': 'RbyR Logo',
            },
        ),
        migrations.CreateModel(
            name='LogoAndNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Images/')),
                ('whatsappNmber', models.BigIntegerField(validators=[back_site.models.validate_phone_number], verbose_name='Whatsapp Number')),
            ],
            options={
                'verbose_name_plural': 'Logo and Number',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=13, unique=True)),
                ('Show_subMenu_with_image', models.BooleanField(default=False)),
                ('show_instant_filter_for_subMenu', models.BooleanField(default=False)),
                ('Choose_menu_type', models.CharField(choices=[('1', 'Show subMenu with image')], default='1', max_length=40, verbose_name='Choose menu display type')),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Online_Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_img', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=18, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True, validators=[back_site.models.validate_phone_number])),
            ],
            options={
                'verbose_name_plural': 'Online Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=18, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, validators=[back_site.models.validate_phone_number])),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('subtitle1', models.CharField(blank=True, max_length=255, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('subtitle2', models.CharField(blank=True, max_length=255, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('menu', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('img_main', models.ImageField(upload_to='Images/')),
                ('img_sub1', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('img_sub2', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('img_sub3', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('like', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(1500000)])),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('fabric', models.CharField(blank=True, max_length=50, null=True)),
                ('made_in', models.CharField(blank=True, max_length=30, null=True)),
                ('style_code', models.CharField(blank=True, max_length=30, null=True)),
                ('XS', models.BigIntegerField(blank=True, null=True)),
                ('S', models.BigIntegerField(blank=True, null=True)),
                ('M', models.BigIntegerField(blank=True, null=True)),
                ('L', models.BigIntegerField(blank=True, null=True)),
                ('XL', models.BigIntegerField(blank=True, null=True)),
                ('XXL', models.BigIntegerField(blank=True, null=True)),
                ('XXXL', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('available', models.BooleanField(default=True)),
                ('shipping_charges', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_days', models.CharField(blank=True, max_length=50, null=True)),
                ('ready_to_ship', models.BooleanField(default=False)),
                ('ready_to_ship_days', models.CharField(blank=True, max_length=50, null=True)),
                ('search_key', models.TextField(blank=True, default='')),
                ('bestSeller', models.BooleanField(default=False)),
                ('careTip', models.CharField(blank=True, max_length=250, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_discount_percentage', models.FloatField(blank=True, default=0.0, null=True, validators=[back_site.models.validate_discount_precentage], verbose_name='Discount in (%)')),
                ('product_price_after_sale', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField(blank=True, null=True)),
                ('subtitle1', models.CharField(blank=True, max_length=255)),
                ('content2', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Return Policy',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkName', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='Images/')),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='StoreLocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(validators=[back_site.models.validate_address])),
                ('phoneNumber', models.BigIntegerField(validators=[back_site.models.validate_phone_number])),
                ('email', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
                ('storeImage', models.ImageField(upload_to='Images/')),
            ],
            options={
                'verbose_name_plural': 'Footer contact details ',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.BigIntegerField(validators=[back_site.models.validate_tax])),
            ],
            options={
                'verbose_name_plural': 'Tax Setting',
            },
        ),
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField(null=True)),
                ('subtitle1', models.CharField(blank=True, max_length=255)),
                ('content2', models.TextField(blank=True, null=True)),
                ('subtitle2', models.CharField(blank=True, max_length=255, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('subtitle3', models.CharField(blank=True, max_length=255, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('subtitle4', models.CharField(blank=True, max_length=255, null=True)),
                ('content5', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Terms & Conditions',
            },
        ),
        migrations.CreateModel(
            name='WomenClothSizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/')),
            ],
            options={
                'verbose_name_plural': "Women's Cloth Size Chart",
            },
        ),
        migrations.CreateModel(
            name='WorldOfRByRContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(blank=True, max_length=400, null=True)),
                ('top_image', models.ImageField(upload_to='Images/')),
                ('title1', models.CharField(max_length=50)),
                ('description1', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About us Section 1',
            },
        ),
        migrations.CreateModel(
            name='worldOfRByRRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='Images/')),
                ('img2', models.ImageField(blank=True, upload_to='Images/')),
                ('img3', models.ImageField(blank=True, upload_to='Images/')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description1', models.TextField(blank=True)),
                ('description2', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'About us Section 2',
            },
        ),
        migrations.CreateModel(
            name='usershippingDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('houseno', models.CharField(max_length=20, verbose_name='House No')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('isSelected', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "User's Shipping Details",
            },
        ),
        migrations.CreateModel(
            name='userbillingDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('houseno', models.CharField(max_length=20, verbose_name='House No')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "User's Billing Details",
            },
        ),
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.BigIntegerField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('shipping_price', models.BigIntegerField(verbose_name='Shipping charges')),
                ('subtotal_price', models.BigIntegerField(verbose_name='Subtotal')),
                ('grand_total', models.BigIntegerField()),
                ('date', models.DateField(auto_now=True, verbose_name='ordered date')),
                ('firstname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('houseno', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('zipcode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User email')),
            ],
            options={
                'verbose_name_plural': 'Transaction Histories',
            },
        ),
        migrations.CreateModel(
            name='subMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/')),
                ('sub', models.CharField(max_length=30, unique=True, verbose_name='Sub menu')),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.menus')),
            ],
        ),
        migrations.CreateModel(
            name='product_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.BigIntegerField()),
                ('product_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('size', models.CharField(max_length=40)),
                ('quantity', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('product_price_after_sale', models.FloatField(blank=True, default=0.0)),
                ('product_discount_price', models.FloatField(blank=True, default=0.0)),
                ('total_price', models.BigIntegerField()),
                ('shipping_charges', models.BigIntegerField(blank=True, default=100, null=True)),
                ('grand_total', models.FloatField(blank=True, default=0.0)),
                ('payment_mode', models.CharField(default='cod', max_length=20)),
                ('date', models.DateField(auto_now_add=True, verbose_name='purchase date')),
                ('selected_currency_sign', models.CharField(max_length=255)),
                ('selected_currency_value', models.FloatField()),
                ('order_status', models.CharField(blank=True, choices=[('Proccessing', 'In Process'), ('Accepted', 'Accepted'), ('Out for Shipping', 'Out for Shipping'), ('Shipped', 'Shipped'), ('Arrived', 'Arrived'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='In Process', max_length=50, null=True, verbose_name='Item status')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_orders/')),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.userbillingdetail', verbose_name='Billing Address')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail')),
                ('shipping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.usershippingdetail', verbose_name='Shipping Address')),
                ('user_no', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Orders',
            },
        ),
        migrations.AddField(
            model_name='product_detail',
            name='subMenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.submenu'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='upper_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.menus'),
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User email')),
            ],
            options={
                'verbose_name_plural': 'Wishlist Of Users',
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='HomeNormalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/')),
                ('menu', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('Menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.menus')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.submenu')),
            ],
        ),
        migrations.CreateModel(
            name='HomeGifImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gif_image', models.ImageField(upload_to='Images/')),
                ('menu', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('Menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.menus')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.submenu')),
            ],
        ),
        migrations.CreateModel(
            name='Head_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='Images/', verbose_name='Home image')),
                ('category', models.CharField(max_length=50)),
                ('display_on', models.CharField(choices=[('window', 'For Window'), ('Mobile', 'For Mobile')], default='window', max_length=20)),
                ('Menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.menus')),
            ],
            options={
                'verbose_name_plural': 'Home Images',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopImage1', models.ImageField(upload_to='Images/')),
                ('ModelName', models.CharField(max_length=50)),
                ('MagzineName', models.CharField(max_length=200)),
                ('menu', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail')),
                ('subMenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.submenu')),
                ('upper_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.menus')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTailoredForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('contactNumber', models.BigIntegerField()),
                ('shoulder', models.CharField(blank=True, max_length=255)),
                ('chest', models.CharField(blank=True, max_length=255)),
                ('upperChest', models.CharField(blank=True, max_length=255)),
                ('lowerChest', models.CharField(blank=True, max_length=255)),
                ('dartPoint', models.CharField(blank=True, max_length=255)),
                ('armhole', models.CharField(blank=True, max_length=255)),
                ('armround', models.CharField(blank=True, max_length=255)),
                ('waist', models.CharField(blank=True, max_length=255)),
                ('lowerWaist', models.CharField(blank=True, max_length=255)),
                ('hips', models.CharField(blank=True, max_length=255)),
                ('length', models.CharField(blank=True, max_length=255)),
                ('otherInstructions', models.TextField(blank=True, default='')),
                ('product_name', models.CharField(blank=True, max_length=250, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail')),
            ],
            options={
                'verbose_name_plural': 'Custom Tailored Requests',
            },
        ),
        migrations.CreateModel(
            name='CurrencySelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('currency_sign', models.CharField(max_length=255)),
                ('currency_value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='couponUsed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('used', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopImage1', models.ImageField(upload_to='Images/')),
                ('ModelName', models.CharField(max_length=50)),
                ('productTitle', models.CharField(max_length=200)),
                ('menu', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail')),
                ('subMenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.submenu')),
                ('upper_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back_site.menus')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=1)),
                ('size', models.CharField(choices=[('Extra Short', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('Extra Extra Large', 'XXL'), ('Extra Extra Extra Large', 'XXL')], default='Small', max_length=40)),
                ('product_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail', verbose_name='Product name')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Cart Of User',
            },
        ),
    ]
