# Generated by Django 4.1.3 on 2023-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
