# Generated by Django 4.1.3 on 2024-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
