# Generated by Django 4.1.1 on 2022-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
