# Generated by Django 4.1.3 on 2023-10-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0002_alter_product_detail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
