# Generated by Django 4.1.3 on 2024-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0002_product_orders_is_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orders',
            name='is_sale',
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='is_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
