# Generated by Django 4.1.3 on 2023-10-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0003_alter_product_detail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldofrbyrcontent',
            name='video_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
