# Generated by Django 4.1.3 on 2024-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0003_remove_product_orders_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='is_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
