# Generated by Django 4.1.3 on 2023-10-28 09:14

import back_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0004_alter_worldofrbyrcontent_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoandnumber',
            name='whatsappNmber',
            field=models.BigIntegerField(validators=[back_site.models.validate_phone_number], verbose_name='Whatsapp Number'),
        ),
    ]
