# Generated by Django 4.1.1 on 2022-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='category',
            field=models.CharField(default='special', max_length=50),
        ),
    ]
