# Generated by Django 4.1.3 on 2024-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0005_alter_product_detail_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
