# Generated by Django 4.1.3 on 2024-07-18 06:48

import back_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0006_alter_product_detail_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='sale_discount_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[back_site.models.validate_discount_precentage], verbose_name='Discount in (%)'),
        ),
    ]
