# Generated by Django 4.1.1 on 2022-10-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0006_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=None)),
            ],
        ),
    ]
