# Generated by Django 4.1.1 on 2022-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0007_imagefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='None/')),
            ],
        ),
        migrations.DeleteModel(
            name='Head_image',
        ),
        migrations.DeleteModel(
            name='imageField',
        ),
    ]
