# Generated by Django 4.1.1 on 2022-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0008_head_img_delete_head_image_delete_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='img_main',
            field=models.ImageField(upload_to='None/'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
