# Generated by Django 4.1.1 on 2022-10-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0010_cart_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_buy',
            name='size',
            field=models.CharField(default='m', max_length=10),
        ),
    ]
