# Generated by Django 4.1.1 on 2022-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0012_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='img_sub1',
            field=models.ImageField(default='null', upload_to='None/'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='img_sub2',
            field=models.ImageField(default='null', upload_to='None/'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='img_sub3',
            field=models.ImageField(default='null', upload_to='None/'),
        ),
    ]
