# Generated by Django 4.1.1 on 2022-10-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0013_product_detail_img_sub1_product_detail_img_sub2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='category',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('puja', 'Puja'), ('casual', 'Lounge'), ('lounge', 'Formal'), ('formal', 'Formal')], default='casual', max_length=50),
        ),
    ]
