# Generated by Django 4.1.1 on 2022-10-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0014_alter_product_detail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='color',
            field=models.CharField(default='blue', max_length=25),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='category',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal')], default='casual', max_length=50),
        ),
    ]
