# Generated by Django 4.1.1 on 2022-10-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0015_product_detail_color_alter_product_detail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='L',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='M',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='S',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='XL',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='XXL',
            field=models.IntegerField(default=30),
        ),
    ]
