# Generated by Django 4.1.1 on 2022-10-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0016_product_detail_l_product_detail_m_product_detail_s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCard_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_top1', models.ImageField(upload_to='None/')),
                ('category_top1', models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal')], default='casual', max_length=50)),
                ('img_top1_1', models.ImageField(upload_to='None/')),
                ('category_top1_1', models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal')], default='casual', max_length=50)),
                ('img_top2', models.ImageField(upload_to='None/')),
                ('category_top2', models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal')], default='casual', max_length=50)),
                ('img_top2_1', models.ImageField(upload_to='None/')),
                ('category_top2_1', models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal')], default='casual', max_length=50)),
                ('img_top3', models.ImageField(upload_to='None/')),
                ('category_top3', models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal')], default='casual', max_length=50)),
                ('img_top4', models.ImageField(upload_to='None/')),
                ('category_top4', models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal')], default='casual', max_length=50)),
            ],
        ),
    ]
