# Generated by Django 4.1.1 on 2022-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0017_homecard_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecard_img',
            name='video_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='homecard_img',
            name='category_top1',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecard_img',
            name='category_top1_1',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecard_img',
            name='category_top2',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecard_img',
            name='category_top2_1',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecard_img',
            name='category_top3',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecard_img',
            name='category_top4',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='category',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
    ]
