# Generated by Django 4.1.1 on 2022-10-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0018_homecard_img_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_img',
            name='about',
            field=models.CharField(default='here you have to write something', max_length=200),
        ),
        migrations.AddField(
            model_name='head_img',
            name='label',
            field=models.CharField(default='slider', max_length=100),
        ),
    ]
