# Generated by Django 4.1.1 on 2022-10-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0019_head_img_about_head_img_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_img',
            name='category',
            field=models.CharField(choices=[('partywear', 'Party wear'), ('kurti', 'Kurti'), ('casual', 'Casual'), ('weddingwear', 'Wedding Wear'), ('formal', 'Formal'), ('luxurypret', 'Luxury'), ('readytowear', 'ready to wear'), ('worldofrr', 'world of rr')], default='casual', max_length=50),
        ),
    ]
