# Generated by Django 4.1.1 on 2022-10-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0020_head_img_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='description',
            field=models.CharField(default='Draped Halter Top With Cutout And Handkerchief Drape', max_length=300),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='fabric',
            field=models.CharField(default='Chiffon', max_length=50),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='made_in',
            field=models.CharField(default='India', max_length=30),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='style_code',
            field=models.CharField(default='AAIR-129-KTH', max_length=30),
        ),
    ]
