# Generated by Django 4.1.1 on 2022-10-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0021_product_detail_description_product_detail_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
    ]
