# Generated by Django 4.1.1 on 2022-10-28 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0028_alter_user_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
