# Generated by Django 4.1.1 on 2022-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0029_alter_user_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='billingDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('houseno', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='shippingDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('houseno', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
    ]
