# Generated by Django 4.1.1 on 2022-11-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0030_billingdetail_shippingdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='billingDetail',
            new_name='userbillingDetail',
        ),
        migrations.RenameModel(
            old_name='shippingDetail',
            new_name='usershippingDetail',
        ),
    ]
