# Generated by Django 4.1.1 on 2022-11-02 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0031_rename_billingdetail_userbillingdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.userbillingdetail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.product_detail')),
                ('shipping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_site.usershippingdetail')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
