# Generated by Django 4.1.1 on 2022-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0032_product_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='purchase date'),
        ),
    ]
