# Generated by Django 4.1.1 on 2022-11-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0034_userbillingdetail_user_id_usershippingdetail_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='payment_mode',
            field=models.CharField(default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='product_orders',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
