# Generated by Django 4.1.1 on 2022-11-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0036_transaction_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orders',
            name='shipping_id',
        ),
    ]
