# Generated by Django 4.1.1 on 2022-11-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0038_product_orders_shipping_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orders',
            name='shipping_id',
        ),
    ]
