# Generated by Django 4.1.1 on 2022-11-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0039_remove_product_orders_shipping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orders',
            name='shipping_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_site.usershippingdetail'),
            preserve_default=False,
        ),
    ]
