# Generated by Django 4.1.1 on 2022-11-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0042_alter_product_detail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='date',
        ),
    ]
