# Generated by Django 4.1.1 on 2022-11-07 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0043_remove_product_detail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
