# Generated by Django 4.1.1 on 2022-11-07 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0044_product_detail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
