# Generated by Django 4.1.1 on 2022-11-07 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0045_alter_product_detail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
