# Generated by Django 4.1.1 on 2022-11-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0046_alter_product_detail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
