# Generated by Django 4.1.1 on 2022-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0047_product_detail_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_img', models.ImageField(upload_to='None/')),
                ('name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=18)),
                ('upi_id', models.CharField(max_length=50)),
            ],
        ),
    ]
