# Generated by Django 4.1.3 on 2022-11-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0048_online_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promocode', models.CharField(max_length=10)),
                ('discount_percentage', models.IntegerField()),
                ('maximum_discount_price', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
