# Generated by Django 4.1.3 on 2022-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0049_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='shipping_charges',
            field=models.IntegerField(default=100),
        ),
    ]
