# Generated by Django 4.1.3 on 2022-11-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0051_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNoticeToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point1', models.CharField(max_length=200)),
                ('point2', models.CharField(max_length=200)),
                ('point3', models.CharField(max_length=200)),
            ],
        ),
    ]
