# Generated by Django 4.1.3 on 2022-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0052_importantnoticetobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='coupon_discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='grand_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='shipping_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='subtotal_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='tax',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
