# Generated by Django 4.1.3 on 2022-11-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0053_transaction_history_coupon_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle1', models.TextField()),
                ('subtitle2', models.TextField()),
                ('bridalImage', models.ImageField(upload_to='None/')),
            ],
        ),
        migrations.CreateModel(
            name='BridalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contactNumber', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('dateOfWedding', models.DateTimeField()),
                ('termsAndCondition', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('subtitle1', models.CharField(max_length=255)),
                ('content2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('subtitle2', models.CharField(max_length=255)),
                ('content2', models.TextField()),
                ('subtitle3', models.CharField(max_length=255)),
                ('content3', models.TextField()),
                ('contactUsImage', models.ImageField(default='None/a1.jpg', upload_to='None/')),
            ],
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAndShippingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('title2', models.CharField(max_length=255)),
                ('content2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('unsubscribe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_home_link', models.CharField(max_length=255)),
                ('instagram_post1', models.ImageField(upload_to='None/')),
                ('instagram_post1_link', models.CharField(max_length=255)),
                ('instagram_post2', models.ImageField(upload_to='None/')),
                ('instagram_post2_link', models.CharField(max_length=255)),
                ('instagram_post3', models.ImageField(upload_to='None/')),
                ('instagram_post3_link', models.CharField(max_length=255)),
                ('instagram_post4', models.ImageField(upload_to='None/')),
                ('instagram_post4_link', models.CharField(max_length=255)),
                ('instagram_post5', models.ImageField(upload_to='None/')),
                ('instagram_post5_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('subtitle1', models.CharField(max_length=255)),
                ('content2', models.TextField()),
                ('subtitle2', models.CharField(max_length=255)),
                ('content3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('subtitle1', models.CharField(max_length=255)),
                ('content2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkName', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phoneNumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('timing', models.CharField(max_length=255)),
                ('storeImage', models.ImageField(upload_to='None/')),
            ],
        ),
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('subtitle1', models.CharField(max_length=255)),
                ('content2', models.TextField()),
                ('subtitle2', models.CharField(max_length=255)),
                ('content3', models.TextField()),
                ('subtitle3', models.CharField(max_length=255)),
                ('content4', models.TextField()),
                ('subtitle4', models.CharField(max_length=255)),
                ('content5', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending'), ('cancle', 'cancle')], default='pending', max_length=50),
        ),
    ]
