# Generated by Django 4.1.3 on 2022-11-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0054_bridal_bridalform_cancellationpolicy_contactus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='search_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
