# Generated by Django 4.1.3 on 2022-11-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_site', '0055_product_detail_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingdetail',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
